all: helloWorld my_first_program leapYear calculator calculator_float dice
helloWorld: helloWorld.c
	gcc helloWorld.c -o ../outputs/helloWorld
my_first_program: my_first_program.c
	gcc my_first_program.c -o ../outputs/my_first_program
leapYear: leapYear.c
	gcc leapYear.c -o ../outputs/leapYear
calculator: calculator.c
	gcc calculator.c -o ../outputs/calculator
calculator_float: calculator_float.c
	gcc calculator_float.c -o ../outputs/calculator_float
dice: dice.c
	gcc dice.c -o ../outputs/dice